<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ImageViewer.Core\ImageViewer.Core.csproj" />
    <ProjectReference Include="..\..\src\ImageViewer.App\ImageViewer.App.csproj" />
  </ItemGroup>

</Project>
